version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ai-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ai_story
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask:
    build: .
    container_name: ai-backend
    ports:
      - "5050:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
